name: Man10Jackpot
version: ${project.version}
main: red.man10.man10jackpot.Man10Jackpot
authors: [Sho0,takatronix]
description: Man10Jackpot plugin
website: man10.red
depend: [Vault]
api-version: 1.17
commands:
 mjackpot:
 mj: