name: Man10Jackpot
version: 1.0-SNAPSHOT
main: red.man10.man10jackpot.Man10Jackpot
authors: [Sho0,takatronix]
description: Man10Jackpot plugin
website: man10.red
depend: [vault]
commands:
 mjackpot:
 mj: